name: hive_local_storage
description: A cache helper which uses hive and flutter_secure_storage to make ease to store session and encrypted data
version: 1.0.8
homepage: https://github.com/kishormainali/hive_local_storage
repository: https://github.com/kishormainali/hive_local_storage
topics: ['localstorage','session','cache','hive','securestorage']

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  collection: ">=1.17.0 <2.0.0"
  synchronized: ^3.1.0
  rxdart: ^0.27.7


  
dev_dependencies:

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ">=2.4.5 <3.0.0"

flutter:
