name: hive_local_storage
description: A cache helper which uses hive and flutter_secure_storage to make ease to store session and encrypted data
version: 1.1.3
homepage: https://github.com/kishormainali/hive_local_storage
repository: https://github.com/kishormainali/hive_local_storage
topics:
  - local-storage
  - session
  - cache
  - hive
  - secure-storage

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4

  collection: 1.19.0 # version pinned by flutter sdk
  synchronized: ^3.3.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
