name: hive_local_storage
description: A cache helper which uses hive and flutter_secure_storage to make ease to store session and encrypted data
version: 2.0.0-dev.1
homepage: https://github.com/kishormainali/hive_local_storage
repository: https://github.com/kishormainali/hive_local_storage
topics:
  - local-storage
  - session
  - cache
  - hive
  - secure-storage

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  collection: ">=1.18.0 <2.0.0"
  synchronized: ^3.1.0+1
  rxdart: ^0.27.7

  path_provider: ^2.1.2

  path: any



dev_dependencies:

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ">=2.4.8 <3.0.0"

flutter:
